<script src="{{ asset('vendors/web/jquery/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('vendors/web/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('vendors/web/jarallax/jarallax.min.js') }}"></script>
<script src="{{ asset('vendors/web/jquery-ajaxchimp/jquery.ajaxchimp.min.js') }}"></script>
<script src="{{ asset('vendors/web/jquery-appear/jquery.appear.min.js') }}"></script>
<script src="{{ asset('vendors/web/jquery-circle-progress/jquery.circle-progress.min.js') }}"></script>
<script src="{{ asset('vendors/web/jquery-magnific-popup/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('vendors/web/jquery-validate/jquery.validate.min.js') }}"></script>
<script src="{{ asset('vendors/web/nouislider/nouislider.min.js') }}"></script>
<script src="{{ asset('vendors/web/odometer/odometer.min.js') }}"></script>
<script src="{{ asset('vendors/web/swiper/swiper.min.js') }}"></script>
<script src="{{ asset('vendors/web/tiny-slider/tiny-slider.min.js') }}"></script>
<script src="{{ asset('vendors/web/wnumb/wNumb.min.js') }}"></script>
<script src="{{ asset('vendors/web/wow/wow.js') }}"></script>
<script src="{{ asset('vendors/web/isotope/isotope.js') }}"></script>
<script src="{{ asset('vendors/web/countdown/countdown.min.js') }}"></script>
<script src="{{ asset('vendors/web/owl-carousel/owl.carousel.min.js') }}"></script>
<script src="{{ asset('vendors/web/bxslider/jquery.bxslider.min.js') }}"></script>
<script src="{{ asset('vendors/web/bootstrap-select/js/bootstrap-select.min.js') }}"></script>
<script src="{{ asset('vendors/web/vegas/vegas.min.js') }}"></script>
<script src="{{ asset('vendors/web/jquery-ui/jquery-ui.js') }}"></script>
<script src="{{ asset('vendors/web/timepicker/timePicker.js') }}"></script>
<script src="{{ asset('vendors/web/circleType/jquery.circleType.js') }}"></script>
<script src="{{ asset('vendors/web/circleType/jquery.lettering.min.js') }}"></script>

<!-- template js -->
<script src="{{ asset('js/web/delogis_custom.js') }}"></script>
